#! /bin/sh
OPENSSL_CONF=`pwd`/myopenssl.cnf
RANDFILE=randomfile
export OPENSSL_CONF RANDFILE

if test $# -eq 0 
then
     echo "error, usage: resign.sh X  where the cert req complte name is X_certreq.pem"
     exit 0;
fi
openssl x509 -req -in submitted_requests/$1_certreq.pem -out signed_requests/$1_cert.pem -signkey ca_private_key/ca_key.pem -days 365

